export interface MMPI3Item {
  id: number;
  text: string;
}

export const MMPI3_ITEMS: MMPI3Item[] = [
  { id: 1, text: "My daily life is full of things that keep me interested." },
  { id: 2, text: "I have a good appetite." },
  { id: 3, text: "I often do things on the spur of the moment." },
  { id: 4, text: "I have very special talents that few others have." },
  { id: 5, text: "I don't like to let people get too close to me." },
  { id: 6, text: "I find it hard to keep my mind on a task or job." },
  { id: 7, text: "I love to go dancing." },
  { id: 8, text: "I function well under stress." },
  { id: 9, text: "I am easily irritated." },
  { id: 10, text: "It takes a lot of argument to convince most people of the truth." },
  { id: 11, text: "I have many brilliant ideas." },
  { id: 12, text: "I often feel I can read other people's minds." },
  { id: 13, text: "I get anxious and upset when I have to make a short trip away from home." },
  { id: 14, text: "I don't like it when things are out of place." },
  { id: 15, text: "There seems to be a lump in my throat much of the time." },
  { id: 16, text: "At times I feel like swearing." },
  { id: 17, text: "I feel worthless." },
  { id: 18, text: "I feel weak all over much of the time." },
  { id: 19, text: "The members of my family get along quite well." },
  { id: 20, text: "I am a very sociable person." },
  { id: 21, text: "Sometimes when I was young I stole things." },
  { id: 22, text: "I wish I could be as happy as others seem to be." },
  { id: 23, text: "At times I feel like smashing things." },
  { id: 24, text: "I am easily defeated in an argument." },
  { id: 25, text: "It's hard for me to pay attention." },
  { id: 26, text: "My anxiety sometimes gets out of control." },
  { id: 27, text: "I have often lost out on things because I couldn't make up my mind soon enough." },
  { id: 28, text: "When people do me wrong, I feel I should pay them back just on principle." },
  { id: 29, text: "I am likely to feel disappointments so strongly that I can't put them out of my mind." },
  { id: 30, text: "Most of the time I feel blue." },
  { id: 31, text: "I cannot understand what I read as well as I used to." },
  { id: 32, text: "I think a great many people exaggerate their misfortunes to get sympathy and help from others." },
  { id: 33, text: "I have a cough most of the time." },
  { id: 34, text: "I have tried many different drugs." },
  { id: 35, text: "I frequently have to fight against showing that I am bashful." },
  { id: 36, text: "I have had very peculiar and strange experiences." },
  { id: 37, text: "I like to go to social events where there is lots of loud fun." },
  { id: 38, text: "I've thought about how I might kill myself." },
  { id: 39, text: "I often act quickly without thinking things through." },
  { id: 40, text: "It takes a lot to make me angry." },
  { id: 41, text: "Sometimes I enjoy hurting persons I love." },
  { id: 42, text: "If I don't do things a certain way I get nervous." },
  { id: 43, text: "I am troubled by attacks of nausea and vomiting." },
  { id: 44, text: "I find it hard to talk when I meet new people." },
  { id: 45, text: "I do not always tell the truth." },
  { id: 46, text: "When I am with people, I am bothered by hearing very strange things." },
  { id: 47, text: "I think I'm an extraordinary person." },
  { id: 48, text: "I am certainly lacking in self-confidence." },
  { id: 49, text: "I have enjoyed using marijuana." },
  { id: 50, text: "I am afraid of finding myself in a closet or small closed place." },
  { id: 51, text: "I go on eating binges several times a week." },
  { id: 52, text: "I usually do things in the same fixed order." },
  { id: 53, text: "At times I am all full of energy." },
  { id: 54, text: "I often think about something bad that happened to me." },
  { id: 55, text: "I think most people would lie to get ahead." },
  { id: 56, text: "I spend a lot of time on minor details." },
  { id: 57, text: "I enjoy social gatherings just to be with people." },
  { id: 58, text: "Some of my family have habits that bother and annoy me very much." },
  { id: 59, text: "My memory seems to be all right." },
  { id: 60, text: "I frequently find it necessary to stand up for what I think is right." },
  { id: 61, text: "I have never done anything dangerous for the thrill of it." },
  { id: 62, text: "I am an important person." },
  { id: 63, text: "I have often felt that strangers were looking at me critically." },
  { id: 64, text: "I do many things I regret afterward." },
  { id: 65, text: "I am almost never bothered by pains over my heart or in my chest." },
  { id: 66, text: "In school I was sometimes sent to the principal for bad behavior." },
  { id: 67, text: "I dislike having people around me." },
  { id: 68, text: "I usually have to stop and think before I act even in small matters." },
  { id: 69, text: "My hands have not become clumsy." },
  { id: 70, text: "I read every editorial in the newspaper every day." },
  { id: 71, text: "I believe I am being plotted against." },
  { id: 72, text: "At times my thoughts have raced ahead faster than I could speak them." },
  { id: 73, text: "I believe I am no more nervous than most others." },
  { id: 74, text: "Much of the time I feel as if I have done something wrong or evil." },
  { id: 75, text: "I panic easily." },
  { id: 76, text: "I am bothered by an upset stomach several times a week." },
  { id: 77, text: "I am so touchy on some subjects that I can't talk about them." },
  { id: 78, text: "Nothing seems to give me much pleasure." },
  { id: 79, text: "I have nightmares every few nights." },
  { id: 80, text: "I have very few quarrels with members of my family." },
  { id: 81, text: "At times I have fits of laughing and crying that I cannot control." },
  { id: 82, text: "I've done things on impulse that ended up causing me trouble." },
  { id: 83, text: "I usually feel that life is worthwhile." },
  { id: 84, text: "At times I feel like picking a fist fight with someone." },
  { id: 85, text: "I have never seen a vision." },
  { id: 86, text: "I can express my true feelings only when I drink." },
  { id: 87, text: "Most people are honest chiefly because they are afraid of being caught." },
  { id: 88, text: "I hardly ever feel pain in the back of my neck." },
  { id: 89, text: "I certainly feel useless at times." },
  { id: 90, text: "I am easily embarrassed." },
  { id: 91, text: "I am a very ordinary person." },
  { id: 92, text: "I believe I am being followed." },
  { id: 93, text: "I have recently considered killing myself." },
  { id: 94, text: "I do not mind meeting strangers." },
  { id: 95, text: "Once in a while I put off until tomorrow what I ought to do today." },
  { id: 96, text: "My parents often objected to the kind of people I spent my time with." },
  { id: 97, text: "Generally, I prefer to be by myself." },
  { id: 98, text: "I often worry about terrible things that might happen." },
  { id: 99, text: "Most people will use somewhat unfair means to gain profit or an advantage rather than to lose it." },
  { id: 100, text: "I have made myself vomit to control my weight." },
  { id: 101, text: "Much of the time my head seems to hurt all over." },
  { id: 102, text: "I seem to be about as capable and smart as most others around me." },
  { id: 103, text: "Once in a while I feel hate toward members of my family whom I usually love." },
  { id: 104, text: "I strongly defend my own opinions as a rule." },
  { id: 105, text: "I am happy most of the time." },
  { id: 106, text: "I do certain things over and over." },
  { id: 107, text: "I enjoy the excitement of a crowd." },
  { id: 108, text: "I have several times given up doing a thing because I thought too little of my ability." },
  { id: 109, text: "I feel that I have often been punished without cause." },
  { id: 110, text: "I have had periods in which I carried on activities without knowing later what I had been doing." },
  { id: 111, text: "Sometimes I just can't stop eating." },
  { id: 112, text: "Other people are not as easily stressed as I am." },
  { id: 113, text: "I have little or no trouble with my muscles twitching or jumping." },
  { id: 114, text: "I wish I were not so shy." },
  { id: 115, text: "Sometimes some unimportant thought will run through my mind and bother me for days." },
  { id: 116, text: "It is hard to say \"no\" to my impulses." },
  { id: 117, text: "There is something wrong with my mind." },
  { id: 118, text: "Making changes in my life will be almost impossible." },
  { id: 119, text: "I easily become impatient with people." },
  { id: 120, text: "Most of the time I wish I were dead." },
  { id: 121, text: "It is safer to trust nobody." },
  { id: 122, text: "I have had attacks when I could not control my movements or speech but knew what was going on around me." },
  { id: 123, text: "I worry quite a bit over possible misfortunes." },
  { id: 124, text: "I have never been in love with anyone." },
  { id: 125, text: "My speech is the same as always (not faster or slower, no slurring or hoarseness)." },
  { id: 126, text: "I've made a plan for killing myself." },
  { id: 127, text: "I get angry sometimes." },
  { id: 128, text: "I am easily stressed out." },
  { id: 129, text: "Someone has been trying to poison me." },
  { id: 130, text: "I sometimes make myself vomit after eating." },
  { id: 131, text: "When I get bored I like to stir up a little excitement." },
  { id: 132, text: "Often I cross the street to avoid meeting someone." },
  { id: 133, text: "Everything tastes the same." },
  { id: 134, text: "I am not easily angered." },
  { id: 135, text: "I am often afraid of the dark." },
  { id: 136, text: "I cannot keep my mind on one thing." },
  { id: 137, text: "There seems to be a fullness in my head or nose most of the time." },
  { id: 138, text: "My parents and family find more fault with me than they should." },
  { id: 139, text: "I often hear voices without knowing where they come from." },
  { id: 140, text: "I enjoy many different kinds of play and recreation." },
  { id: 141, text: "I have used alcohol excessively." },
  { id: 142, text: "Most people make friends because friends are likely to be useful to them." },
  { id: 143, text: "Sometimes I start sweating and breathing fast for no apparent reason." },
  { id: 144, text: "I have difficulty starting to do things." },
  { id: 145, text: "We frequently fight when my family gets together." },
  { id: 146, text: "Almost every day something happens to frighten me." },
  { id: 147, text: "I like to let people know where I stand on things." },
  { id: 148, text: "Some people go out of their way to annoy me." },
  { id: 149, text: "I've lost my will to live." },
  { id: 150, text: "Someone has been trying to rob me." },
  { id: 151, text: "Dirt frightens or disgusts me." },
  { id: 152, text: "I feel like giving up quickly when things go wrong." },
  { id: 153, text: "My worries seem to disappear when I get into a crowd of lively friends." },
  { id: 154, text: "My table manners are not quite as good at home as when I am out in company." },
  { id: 155, text: "I get mad easily and then get over it soon." },
  { id: 156, text: "I can remember \"playing sick\" to get out of something." },
  { id: 157, text: "Anyone who is able and willing to work hard has a good chance of succeeding." },
  { id: 158, text: "Life is a strain for me much of the time." },
  { id: 159, text: "I have had blank spells in which my activities were interrupted and I did not know what was going on around me." },
  { id: 160, text: "I have a short temper." },
  { id: 161, text: "Bad words, often terrible words, come into my mind and I cannot get rid of them." },
  { id: 162, text: "I seldom or never have dizzy spells." },
  { id: 163, text: "I wake up fresh and rested most mornings." },
  { id: 164, text: "Lately I have thought a lot about killing myself." },
  { id: 165, text: "People do things just to make me look bad." },
  { id: 166, text: "Sometimes without any reason or even when things are going wrong I feel excitedly happy, \"on top of the world.\"" },
  { id: 167, text: "It makes me nervous to have to wait." },
  { id: 168, text: "There are persons who are trying to steal my thoughts and ideas." },
  { id: 169, text: "The future seems hopeless to me." },
  { id: 170, text: "I sometimes count things over and over." },
  { id: 171, text: "I think nearly anyone would tell a lie to keep out of trouble." },
  { id: 172, text: "Often, even though everything is going fine for me, I feel that I don't care about anything." },
  { id: 173, text: "I can't focus on things for very long." },
  { id: 174, text: "During the past few years I have been well most of the time." },
  { id: 175, text: "I am never happier than when alone." },
  { id: 176, text: "Often I feel as if there is a tight band around my head." },
  { id: 177, text: "I am likely not to speak to people until they speak to me." },
  { id: 178, text: "It would be better if almost all laws were thrown away." },
  { id: 179, text: "Some people go out of their way to keep me from getting ahead." },
  { id: 180, text: "The things that some of my family have done have frightened me." },
  { id: 181, text: "Once a week or oftener I become very excited." },
  { id: 182, text: "I am entirely self-confident." },
  { id: 183, text: "I would rather win than lose in a game." },
  { id: 184, text: "I am a burden to others." },
  { id: 185, text: "Most people inwardly dislike putting themselves out to help other people." },
  { id: 186, text: "I have never had a fit or convulsion." },
  { id: 187, text: "I have sometimes felt that difficulties were piling up so high that I could not overcome them." },
  { id: 188, text: "I have special abilities." },
  { id: 189, text: "I have very few headaches." },
  { id: 190, text: "I have never been in trouble with the law." },
  { id: 191, text: "In walking I am very careful to step over sidewalk cracks." },
  { id: 192, text: "After a bad day, I usually need a few drinks to relax." },
  { id: 193, text: "At times I have been so entertained by the cleverness of some criminals that I have hoped they would get away with it." },
  { id: 194, text: "I am sure I am being talked about." },
  { id: 195, text: "Something exciting will almost always pull me out of it when I am feeling low." },
  { id: 196, text: "I am happiest when I'm alone." },
  { id: 197, text: "I am usually very direct with people I am trying to correct or improve." },
  { id: 198, text: "I shrink from facing a crisis or difficulty." },
  { id: 199, text: "Peculiar odors come to me at times." },
  { id: 200, text: "I have more trouble concentrating than others seem to." },
  { id: 201, text: "I like parties." },
  { id: 202, text: "I have never felt better in my life than I do now." },
  { id: 203, text: "My soul sometimes leaves my body." },
  { id: 204, text: "Even when I am with people I feel lonely much of the time." },
  { id: 205, text: "I often skipped school when I was young." },
  { id: 206, text: "I wish I could stop worrying about things I have said that may have hurt other people's feelings." },
  { id: 207, text: "I have periods in which I feel unusually cheerful without any special reason." },
  { id: 208, text: "I am afraid of using a knife or anything very sharp or pointed." },
  { id: 209, text: "I'm willing to starve myself to be thinner than I am." },
  { id: 210, text: "I do not like everyone I know." },
  { id: 211, text: "I am troubled by discomfort in the pit of my stomach every few days or oftener." },
  { id: 212, text: "I have no enemies who really wish to harm me." },
  { id: 213, text: "People generally demand more respect for their own rights than they are willing to allow for others." },
  { id: 214, text: "Although I am not happy with my life, there is nothing I can do about it now." },
  { id: 215, text: "I often have serious disagreements with people who are close to me." },
  { id: 216, text: "At times I hear so well it bothers me." },
  { id: 217, text: "I very seldom have spells of the blues." },
  { id: 218, text: "At times it has been impossible for me to keep from stealing or shoplifting something." },
  { id: 219, text: "Sometimes I become so excited that I find it hard to get to sleep." },
  { id: 220, text: "I am easily startled." },
  { id: 221, text: "I believe in law enforcement." },
  { id: 222, text: "I seem to make friends about as quickly as others do." },
  { id: 223, text: "I was suspended from school one or more times for bad behavior." },
  { id: 224, text: "I have lost hope." },
  { id: 225, text: "In school I found it very hard to talk in front of the class." },
  { id: 226, text: "Painful memories of a past event keep running through my mind." },
  { id: 227, text: "I have had no difficulty in keeping my balance when walking." },
  { id: 228, text: "I feel anxiety about something or someone almost all the time." },
  { id: 229, text: "At times I think I am no good at all." },
  { id: 230, text: "I have a great deal of stomach trouble." },
  { id: 231, text: "I can easily make people afraid of me and sometimes do for the fun of it." },
  { id: 232, text: "I often lose sleep over worries." },
  { id: 233, text: "People say insulting and vulgar things about me." },
  { id: 234, text: "I am not feeling much pressure or stress these days." },
  { id: 235, text: "I sometimes relive bad experiences." },
  { id: 236, text: "I spend a lot of time making sure things are exactly in the right place." },
  { id: 237, text: "Except by doctor's orders I never take drugs or sleeping pills." },
  { id: 238, text: "I recognize several faults in myself that I will not be able to change." },
  { id: 239, text: "If given the chance I would make a good leader of people." },
  { id: 240, text: "I often feel as if things are not real." },
  { id: 241, text: "Some people are against me for no good reason." },
  { id: 242, text: "The top of my head sometimes feels tender." },
  { id: 243, text: "I gossip a little at times." },
  { id: 244, text: "My heart sometimes starts racing for no apparent reason." },
  { id: 245, text: "Someone has control over my mind." },
  { id: 246, text: "I usually expect to succeed in things I do." },
  { id: 247, text: "I feel tired a good deal of the time." },
  { id: 248, text: "I am often said to be hotheaded." },
  { id: 249, text: "I don't think my abilities amount to much." },
  { id: 250, text: "I am often sorry because I am so irritable and grouchy." },
  { id: 251, text: "No one knows it but I have tried to kill myself." },
  { id: 252, text: "I am an anxious person." },
  { id: 253, text: "In school my marks in classroom behavior were quite regularly bad." },
  { id: 254, text: "Some people will be pleased if I fail." },
  { id: 255, text: "It does not bother me particularly to see animals suffer." },
  { id: 256, text: "I have often met people who were supposed to be experts who were no better than I." },
  { id: 257, text: "I have strange and peculiar thoughts." },
  { id: 258, text: "I have frequently worked for people who seem to have arranged things so they get credit for good work but blame mistakes on those under them." },
  { id: 259, text: "I often act on impulse." },
  { id: 260, text: "I sometimes feel that I am about to go to pieces." },
  { id: 261, text: "I often check things over and over." },
  { id: 262, text: "I am in just as good physical health as most of my friends." },
  { id: 263, text: "I must admit that I have at times been worried beyond reason over something that really did not matter." },
  { id: 264, text: "Someone has it in for me." },
  { id: 265, text: "I have few or no pains." },
  { id: 266, text: "I have a drug or alcohol problem." },
  { id: 267, text: "I have had periods when I felt so full of energy that sleep did not seem necessary for days at a time." },
  { id: 268, text: "I never worry about my looks." },
  { id: 269, text: "When things get really bad, I know I can count on my family for help." },
  { id: 270, text: "At one or more times in my life I felt that someone was making me do things by hypnotizing me." },
  { id: 271, text: "It makes me angry to have people hurry me." },
  { id: 272, text: "I have no trouble swallowing." },
  { id: 273, text: "I hear strange things when I am alone." },
  { id: 274, text: "I usually have a hard time deciding what to do." },
  { id: 275, text: "Several times a week I feel as if something dreadful is about to happen." },
  { id: 276, text: "When people do something that makes me angry, I let them know how I feel about it." },
  { id: 277, text: "I frequently notice my hand shakes when I try to do something." },
  { id: 278, text: "Whenever possible I avoid being in a crowd." },
  { id: 279, text: "Often I get confused and forget what I want to say." },
  { id: 280, text: "My people treat me more like a child than a grown-up." },
  { id: 281, text: "I have difficulty concentrating." },
  { id: 282, text: "My main goals in life are within my reach." },
  { id: 283, text: "Talking over problems and worries with someone is often more helpful than taking drugs or medicine." },
  { id: 284, text: "I think I'm a pretty special person." },
  { id: 285, text: "At times I can't seem to stop talking." },
  { id: 286, text: "I often worry about something more than I should." },
  { id: 287, text: "A sudden noise will often startle me." },
  { id: 288, text: "I often feel that I'm not as good as other people." },
  { id: 289, text: "I have often been frightened in the middle of the night." },
  { id: 290, text: "I find it hard to control my anger." },
  { id: 291, text: "I am never happier than when I am by myself." },
  { id: 292, text: "I do not often notice my ears ringing or buzzing." },
  { id: 293, text: "I am usually calm and not easily upset." },
  { id: 294, text: "I see things or animals or people around me that others do not see." },
  { id: 295, text: "I have no dread of going into a room by myself where other people have already gathered and are talking." },
  { id: 296, text: "I have given up hope of amounting to anything." },
  { id: 297, text: "Once a week or more I get high or drunk." },
  { id: 298, text: "Sometimes in elections I vote for people about whom I know very little." },
  { id: 299, text: "I feel helpless when I have to make some important decisions." },
  { id: 300, text: "I would not be a good leader." },
  { id: 301, text: "I have numbness in one or more places on my skin." },
  { id: 302, text: "I like making decisions and assigning jobs to others." },
  { id: 303, text: "I often become very irritable when people interrupt my work." },
  { id: 304, text: "In most marriages one or both partners are unhappy." },
  { id: 305, text: "I am afraid of being alone in a wide-open place." },
  { id: 306, text: "I forget where I leave things." },
  { id: 307, text: "I would rather not get too close to people." },
  { id: 308, text: "My neck spots with red often." },
  { id: 309, text: "I worry a great deal over money." },
  { id: 310, text: "People are not very kind to me." },
  { id: 311, text: "Sometimes I am sure that other people can tell what I am thinking." },
  { id: 312, text: "I have gotten angry and broken furniture or dishes when I was drinking." },
  { id: 313, text: "I have never been paralyzed or had any unusual weakness of any of my muscles." },
  { id: 314, text: "I hate my whole family." },
  { id: 315, text: "I am so sick of what I have to do every day that I just want to get out of it all." },
  { id: 316, text: "I have at times had to be rough with people who were rude or annoying." },
  { id: 317, text: "I can't go into a dark room alone even in my own home." },
  { id: 318, text: "Sometimes I get so angry and upset I don't know what comes over me." },
  { id: 319, text: "I've used prescription medication to get high." },
  { id: 320, text: "I was arrested as a teenager." },
  { id: 321, text: "I like to drive a hard bargain." },
  { id: 322, text: "Criticism or scolding hurts me terribly." },
  { id: 323, text: "When I am sad, visiting with friends can always pull me out of it." },
  { id: 324, text: "Having to make important decisions makes me nervous." },
  { id: 325, text: "Once in a while I laugh at a dirty joke." },
  { id: 326, text: "I have some outstanding qualities." },
  { id: 327, text: "I am often inclined to go out of my way to win a point with someone who has opposed me." },
  { id: 328, text: "If I get upset I'm sure to get a headache." },
  { id: 329, text: "I've been so angry at times that I've hurt someone in a physical fight." },
  { id: 330, text: "I sometimes seem to hear my thoughts being spoken out loud." },
  { id: 331, text: "When my life gets difficult, it makes me want to just give up." },
  { id: 332, text: "If people had not had it in for me, I would have been much more successful." },
  { id: 333, text: "I do not tire quickly." },
  { id: 334, text: "I have become so angry with someone that I have felt as if I would explode." },
  { id: 335, text: "I frequently find myself worrying about something." }
];
